import sys
from pathlib import Path
from unittest.mock import patch

from django.urls import NoReverseMatch, reverse
from rest_framework import status
from rest_framework.test import APITestCase
from django.core.files.uploadedfile import SimpleUploadedFile

from core.models import ChatSession, ChatMessage


AI_SERVICES_DIR = Path(__file__).resolve().parents[2] / "ai-services"
if str(AI_SERVICES_DIR) not in sys.path:
    sys.path.append(str(AI_SERVICES_DIR))

from ollama_client import extract_metadata


class RecallOSServerTests(APITestCase):
    def setUp(self):
        self.client.credentials()

    def test_persistent_document_routes_are_removed(self):
        for route_name in (
            "document-list",
            "document-detail",
            "document-summarize",
            "semantic_search",
        ):
            with self.subTest(route_name=route_name):
                with self.assertRaises(NoReverseMatch):
                    if route_name in {"document-detail", "document-summarize"}:
                        reverse(route_name, kwargs={"pk": "00000000-0000-0000-0000-000000000000"})
                    else:
                        reverse(route_name)

    @patch('core.views.extract_metadata')
    def test_transient_document_processing_returns_chunks_without_storing_file(self, mock_metadata):
        mock_metadata.return_value = {
            "suggested_title": "Local First Notes",
            "summary": "A short summary generated by the server fallback.",
            "category": "Technology",
            "tags": ["local-first", "fallback"],
        }
        upload_url = reverse('document_process')
        uploaded_file = SimpleUploadedFile(
            "local-first.txt",
            b"Client first document text. It should be processed without being persisted.",
            content_type="text/plain",
        )

        response = self.client.post(upload_url, {"file": uploaded_file}, format='multipart')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["filename"], "local-first.txt")
        self.assertEqual(response.data["file_type"], "text")
        self.assertEqual(response.data["summary"], "A short summary generated by the server fallback.")
        self.assertGreaterEqual(len(response.data["chunks"]), 1)
        self.assertEqual(ChatSession.objects.count(), 0)
        self.assertEqual(ChatMessage.objects.count(), 0)

    @patch('ollama_client.generate_completion')
    def test_extract_metadata_generates_llm_summary_when_json_summary_missing(self, mock_completion):
        document_text = (
            "This is the first indexed text portion and should not be reused as the summary. "
            "It contains implementation details, line items, and raw document phrasing. "
            "Later sections describe a local-first AI workspace for document search and chat."
        )
        ai_summary = "The document describes a local-first AI workspace that indexes uploaded files and supports semantic search with contextual chat."
        mock_completion.side_effect = [
            '{"suggested_title": "Workspace Notes", "category": "Technology", "tags": ["AI", "search"]}',
            ai_summary,
        ]

        metadata = extract_metadata(document_text, fallback_title="workspace.txt")

        self.assertEqual(metadata['summary'], ai_summary)
        self.assertNotEqual(metadata['summary'], document_text[:len(metadata['summary'])])
        self.assertEqual(mock_completion.call_count, 2)

    @patch('ollama_client.generate_completion')
    def test_extract_metadata_regenerates_summary_when_json_summary_copies_source(self, mock_completion):
        copied_summary = "This is the first indexed text portion and should not be reused as the summary."
        document_text = (
            f"{copied_summary} It contains implementation details and raw document phrasing. "
            "Later sections describe a local-first AI workspace for document search and chat."
        )
        ai_summary = "The document describes a local-first AI workspace for indexing documents and chatting with retrieved context."
        mock_completion.side_effect = [
            f'{{"suggested_title": "Workspace Notes", "summary": "{copied_summary}", "category": "Technology", "tags": ["AI"]}}',
            ai_summary,
        ]

        metadata = extract_metadata(document_text, fallback_title="workspace.txt")

        self.assertEqual(metadata['summary'], ai_summary)
        self.assertEqual(mock_completion.call_count, 2)

    @patch('core.views.generate_completion')
    def test_chat_session_and_message_without_server_document_search(self, mock_completion):
        mock_completion.return_value = "The answer uses the supplied local context."

        session_response = self.client.post(reverse('chatsession-list'), {
            "title": "Local Context Dialogue"
        }, format='json')
        self.assertEqual(session_response.status_code, status.HTTP_201_CREATED)
        session_id = session_response.data['id']

        message_url = reverse('chat_message_create', kwargs={"session_id": session_id})
        message_response = self.client.post(message_url, {
            "content": "Where did I work?",
            "context_chunks": [
                {
                    "document_id": "local-123",
                    "filename": "CV.pdf",
                    "suggested_title": "CV",
                    "chunk_index": 2,
                    "page_number": 1,
                    "section_title": "Experience",
                    "content_type": "paragraph",
                    "reason": "list_all_expansion",
                    "entities": {"organizations": ["Acme Technologies Ltd"]},
                    "content": "Experience: Acme Technologies Ltd, Backend Engineer.",
                }
            ],
        }, format='json')

        self.assertEqual(message_response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(message_response.data['role'], 'assistant')
        self.assertEqual(message_response.data['content'], "The answer uses the supplied local context.")
        self.assertEqual(message_response.data['sources'][0]['document_id'], 'local-123')
        self.assertEqual(message_response.data['sources'][0]['section_title'], 'Experience')

        detail_response = self.client.get(reverse('chatsession-detail', kwargs={"pk": session_id}))
        self.assertEqual(detail_response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(detail_response.data['messages']), 2)

    @patch('core.views.requests.get')
    def test_model_list_marks_supported_installed_ollama_models(self, mock_get):
        mock_get.return_value.status_code = status.HTTP_200_OK
        mock_get.return_value.json.return_value = {
            "models": [
                {"name": "gemma4:e2b", "size": int(6.7 * 1024 * 1024 * 1024)},
            ]
        }

        response = self.client.get(reverse('models_list'))

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        models = response.data['models']
        names = [model['name'] for model in models]
        self.assertEqual(names, ['gemma4:e2b'])
        self.assertTrue(all(model['installed'] for model in models))
