import sys
from pathlib import Path
from unittest.mock import patch

from django.urls import NoReverseMatch, reverse
from rest_framework import status
from rest_framework.test import APITestCase
from django.core.files.uploadedfile import SimpleUploadedFile

from core.models import ChatSession, ChatMessage
from core.views import (
    apply_llm_route_to_inventory,
    build_agentic_tool_request,
    build_deterministic_metadata_answer,
    parse_query_intent_response,
    parse_structured_llm_response,
    resolve_answer_sources,
)


AI_SERVICES_DIR = Path(__file__).resolve().parents[2] / "ai-services"
if str(AI_SERVICES_DIR) not in sys.path:
    sys.path.append(str(AI_SERVICES_DIR))

from groq_client import (
    GROQ_MODEL,
    extract_metadata,
    generate_completion,
    generate_vision_completion,
)
from ollama_client import OLLAMA_EMBEDDING_MODEL, generate_embeddings
from ollama_llm_client import OLLAMA_LLM_MODEL, generate_ollama_llm_completion


class RecallOSServerTests(APITestCase):
    def setUp(self):
        self.client.credentials()

    def test_persistent_document_routes_are_removed(self):
        for route_name in (
            "document-list",
            "document-detail",
            "document-summarize",
            "semantic_search",
        ):
            with self.subTest(route_name=route_name):
                with self.assertRaises(NoReverseMatch):
                    if route_name in {"document-detail", "document-summarize"}:
                        reverse(route_name, kwargs={"pk": "00000000-0000-0000-0000-000000000000"})
                    else:
                        reverse(route_name)

    @patch('core.views.extract_metadata')
    def test_transient_document_processing_returns_chunks_without_storing_file(self, mock_metadata):
        mock_metadata.return_value = {
            "suggested_title": "Local First Notes",
            "summary": "A short summary generated by the server fallback.",
            "category": "Technology",
            "tags": ["local-first", "fallback"],
        }
        upload_url = reverse('document_process')
        uploaded_file = SimpleUploadedFile(
            "local-first.txt",
            b"Client first document text. It should be processed without being persisted.",
            content_type="text/plain",
        )

        response = self.client.post(upload_url, {"file": uploaded_file}, format='multipart')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["filename"], "local-first.txt")
        self.assertEqual(response.data["file_type"], "text")
        self.assertEqual(response.data["summary"], "A short summary generated by the server fallback.")
        self.assertGreaterEqual(len(response.data["chunks"]), 1)
        self.assertEqual(ChatSession.objects.count(), 0)
        self.assertEqual(ChatMessage.objects.count(), 0)

    @patch('core.views.generate_document_summary')
    def test_transient_document_summary_generates_from_extracted_text(self, mock_summary):
        mock_summary.return_value = "The AI summary explains the document's purpose without copying the first chunk."

        response = self.client.post(reverse('document_summary'), {
            "text": "First chunk text should not be reused directly. Later text explains the document purpose.",
            "filename": "notes.txt",
        }, format='json')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["summary"], "The AI summary explains the document's purpose without copying the first chunk.")
        mock_summary.assert_called_once_with(
            "First chunk text should not be reused directly. Later text explains the document purpose.",
            fallback_title="notes.txt",
            model_profile="text",
        )
        self.assertEqual(ChatSession.objects.count(), 0)
        self.assertEqual(ChatMessage.objects.count(), 0)

    @patch('core.views.generate_document_category')
    def test_transient_document_category_uses_summary_and_chunks(self, mock_category):
        mock_category.return_value = "Technology"

        response = self.client.post(reverse('document_category'), {
            "filename": "notes.txt",
            "summary": "A summary about semantic document search and local AI.",
            "chunks": [
                {"content": "The system indexes chunks with embeddings for RAG search."},
                {"text": "Users can ask questions over their local knowledge base."},
            ],
        }, format='json')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["category"], "Technology")
        mock_category.assert_called_once_with(
            "The system indexes chunks with embeddings for RAG search.\n\nUsers can ask questions over their local knowledge base.",
            summary="A summary about semantic document search and local AI.",
            fallback_title="notes.txt",
            model_profile="text",
        )

    @patch('groq_client.generate_completion')
    def test_extract_metadata_generates_llm_summary_when_json_summary_missing(self, mock_completion):
        document_text = (
            "This is the first indexed text portion and should not be reused as the summary. "
            "It contains implementation details, line items, and raw document phrasing. "
            "Later sections describe a local-first AI workspace for document search and chat."
        )
        ai_summary = "The document describes a local-first AI workspace that indexes uploaded files and supports semantic search with contextual chat."
        mock_completion.side_effect = [
            '{"suggested_title": "Workspace Notes", "category": "Technology", "tags": ["AI", "search"]}',
            ai_summary,
        ]

        metadata = extract_metadata(document_text, fallback_title="workspace.txt")

        self.assertEqual(metadata['summary'], ai_summary)
        self.assertNotEqual(metadata['summary'], document_text[:len(metadata['summary'])])
        self.assertEqual(mock_completion.call_count, 2)

    @patch('groq_client.generate_completion')
    def test_extract_metadata_regenerates_summary_when_json_summary_copies_source(self, mock_completion):
        copied_summary = "This is the first indexed text portion and should not be reused as the summary."
        document_text = (
            f"{copied_summary} It contains implementation details and raw document phrasing. "
            "Later sections describe a local-first AI workspace for document search and chat."
        )
        ai_summary = "The document describes a local-first AI workspace for indexing documents and chatting with retrieved context."
        mock_completion.side_effect = [
            f'{{"suggested_title": "Workspace Notes", "summary": "{copied_summary}", "category": "Technology", "tags": ["AI"]}}',
            ai_summary,
        ]

        metadata = extract_metadata(document_text, fallback_title="workspace.txt")

        self.assertEqual(metadata['summary'], ai_summary)
        self.assertEqual(mock_completion.call_count, 2)

    @patch('core.views.generate_completion')
    def test_chat_session_and_message_without_server_document_search(self, mock_completion):
        mock_completion.return_value = "The answer uses the supplied local context. [S1]"

        session_response = self.client.post(reverse('chatsession-list'), {
            "title": "Local Context Dialogue"
        }, format='json')
        self.assertEqual(session_response.status_code, status.HTTP_201_CREATED)
        session_id = session_response.data['id']

        message_url = reverse('chat_message_create', kwargs={"session_id": session_id})
        message_response = self.client.post(message_url, {
            "content": "Where did I work?",
            "query_mode": "semantic_lookup",
            "context_chunks": [
                {
                    "document_id": "local-123",
                    "filename": "CV.pdf",
                    "suggested_title": "CV",
                    "chunk_index": 2,
                    "page_number": 1,
                    "section_title": "Experience",
                    "content_type": "paragraph",
                    "reason": "list_all_expansion",
                    "entities": {"organizations": ["Acme Technologies Ltd"]},
                    "content": "Experience: Acme Technologies Ltd, Backend Engineer.",
                }
            ],
        }, format='json')

        self.assertEqual(message_response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(message_response.data['role'], 'assistant')
        self.assertEqual(message_response.data['content'], "The answer uses the supplied local context.")
        self.assertEqual(message_response.data['sources'][0]['document_id'], 'local-123')
        self.assertEqual(message_response.data['sources'][0]['section_title'], 'Experience')

        detail_response = self.client.get(reverse('chatsession-detail', kwargs={"pk": session_id}))
        self.assertEqual(detail_response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(detail_response.data['messages']), 2)

    @patch('core.views.generate_completion')
    def test_chat_message_sources_include_only_cited_context_documents(self, mock_completion):
        mock_completion.return_value = "The requested text is about local AI memory. [S2]"

        session_response = self.client.post(reverse('chatsession-list'), {
            "title": "Source Filtering"
        }, format='json')
        session_id = session_response.data['id']

        message_response = self.client.post(reverse('chat_message_create', kwargs={"session_id": session_id}), {
            "content": "What is large_test_text_english.txt about?",
            "query_mode": "semantic_lookup",
            "context_chunks": [
                {
                    "document_id": "cv-doc",
                    "filename": "CV_Fedor_Rumiantsev.pdf",
                    "suggested_title": "CV Fedor",
                    "chunk_index": 0,
                    "page_number": 1,
                    "section_title": "Experience",
                    "content": "Experience and employment history.",
                },
                {
                    "document_id": "large-text-doc",
                    "filename": "large_test_text_english.txt",
                    "suggested_title": "large_test_text_english.txt",
                    "chunk_index": 0,
                    "page_number": 1,
                    "section_title": "Document",
                    "content": "This text discusses local AI memory systems.",
                },
            ],
        }, format='json')

        self.assertEqual(message_response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(message_response.data['content'], "The requested text is about local AI memory.")
        self.assertEqual(len(message_response.data['sources']), 1)
        self.assertEqual(message_response.data['sources'][0]['document_id'], 'large-text-doc')

    def test_library_inventory_message_accepts_missing_scope_filters(self):
        session_response = self.client.post(reverse('chatsession-list'), {
            "title": "Inventory Chat"
        }, format='json')
        session_id = session_response.data['id']

        message_response = self.client.post(reverse('chat_message_create', kwargs={"session_id": session_id}), {
            "content": "Which documents do I have in my library?",
            "query_mode": "library_inventory",
            "scope": {},
            "context_chunks": [
                {
                    "document_id": "local-doc-1",
                    "filename": "notes.md",
                    "suggested_title": "Project Notes",
                    "section_title": "Library Inventory",
                    "content_type": "document_metadata",
                    "reason": "library_inventory",
                    "content": "Filename: notes.md\nSuggested title: Project Notes",
                }
            ],
        }, format='json')

        self.assertEqual(message_response.status_code, status.HTTP_201_CREATED)
        self.assertIn("Found 1 document", message_response.data["content"])
        self.assertNotIn("В библиотеке", message_response.data["content"])
        self.assertIn("Project Notes", message_response.data["content"])
        self.assertEqual(message_response.data["sources"][0]["document_id"], "local-doc-1")

    def test_answer_sources_do_not_fallback_to_multiple_uncited_candidates(self):
        candidate_sources_by_ref = {
            "S1": {"source_ref": "S1", "document_id": "cv-doc", "filename": "CV.pdf"},
            "S2": {"source_ref": "S2", "document_id": "readme-doc", "filename": "README.md"},
        }

        sources = resolve_answer_sources(
            candidate_sources_by_ref,
            cited_refs=[],
            query_mode="semantic_lookup",
        )

        self.assertEqual(sources, [])

    def test_answer_sources_fallback_to_single_uncited_candidate(self):
        candidate_sources_by_ref = {
            "S1": {"source_ref": "S1", "document_id": "story-doc", "filename": "story.txt"},
        }

        sources = resolve_answer_sources(
            candidate_sources_by_ref,
            cited_refs=[],
            query_mode="semantic_lookup",
        )

        self.assertEqual([source["document_id"] for source in sources], ["story-doc"])

    def test_answer_sources_include_inventory_candidates_for_metadata_modes(self):
        candidate_sources_by_ref = {
            "S1": {"source_ref": "S1", "document_id": "city-doc", "filename": "city_architecture.txt"},
            "S2": {"source_ref": "S2", "document_id": "large-doc", "filename": "large_test_text_english.txt"},
        }

        sources = resolve_answer_sources(
            candidate_sources_by_ref,
            cited_refs=["S1"],
            query_mode="extension_filter",
        )

        self.assertEqual([source["document_id"] for source in sources], ["city-doc", "large-doc"])

    def test_deterministic_metadata_answer_lists_inventory_without_llm(self):
        candidate_sources_by_ref = {
            "S1": {
                "source_ref": "S1",
                "document_id": "city-doc",
                "filename": "city_architecture.txt",
                "suggested_title": "city_architecture.txt",
            },
            "S2": {
                "source_ref": "S2",
                "document_id": "large-doc",
                "filename": "large_test_text_english.txt",
                "suggested_title": "large_test_text_english.txt",
            },
        }

        answer = build_deterministic_metadata_answer(
            query_mode="extension_filter",
            scope={"filters": {"extension": "txt"}},
            candidate_sources_by_ref=candidate_sources_by_ref,
        )

        self.assertIn("Найдено 2 .txt документа", answer)
        self.assertIn("city_architecture.txt", answer)
        self.assertIn("large_test_text_english.txt", answer)

    def test_deterministic_metadata_answer_matches_english_user_language(self):
        candidate_sources_by_ref = {
            "S1": {
                "source_ref": "S1",
                "document_id": "notes-doc",
                "filename": "notes.md",
                "suggested_title": "Project Notes",
            },
        }

        answer = build_deterministic_metadata_answer(
            query_mode="library_inventory",
            scope={"filters": {}},
            candidate_sources_by_ref=candidate_sources_by_ref,
            user_language="en",
        )

        self.assertIn("Found 1 document", answer)
        self.assertIn("Project Notes", answer)
        self.assertNotIn("В библиотеке", answer)

    def test_parse_structured_llm_response_reads_answer_and_used_document_ids(self):
        parsed = parse_structured_llm_response(
            '{"answer": "Ответ по документу.", "used_document_ids": ["doc-2"], "confidence": "high"}'
        )

        self.assertEqual(parsed["answer"], "Ответ по документу.")
        self.assertEqual(parsed["used_document_ids"], ["doc-2"])
        self.assertEqual(parsed["confidence"], "high")

    def test_parse_structured_llm_response_falls_back_to_legacy_text(self):
        parsed = parse_structured_llm_response("Legacy answer [S1]")

        self.assertEqual(parsed["answer"], "Legacy answer [S1]")
        self.assertEqual(parsed["used_document_ids"], [])

    def test_parse_query_intent_response_reads_multilingual_router_json(self):
        parsed = parse_query_intent_response(
            '{"query_mode": "extension_filter", "filters": {"extension": "txt"}, '
            '"document_ids": ["doc-1"], "needs_semantic_context": false, "confidence": "high"}'
        )

        self.assertEqual(parsed["query_mode"], "extension_filter")
        self.assertEqual(parsed["scope"]["filters"], {"extension": "txt"})
        self.assertEqual(parsed["scope"]["document_ids"], ["doc-1"])
        self.assertEqual(parsed["retrieval"]["strategy"], "metadata_inventory")

    def test_apply_llm_route_to_inventory_filters_extension_after_llm_router(self):
        route = parse_query_intent_response(
            '{"query_mode": "extension_filter", "filters": {"extension": "txt"}, '
            '"needs_semantic_context": false}'
        )
        inventory_items = [
            {"document_id": "doc-1", "filename": "city_architecture.txt", "content": "Filename: city_architecture.txt"},
            {"document_id": "doc-2", "filename": "README.md", "content": "Filename: README.md"},
            {"document_id": "doc-3", "filename": "large_test_text_english.txt", "content": "Filename: large_test_text_english.txt"},
        ]

        filtered_items, resolved_route = apply_llm_route_to_inventory(route, inventory_items)

        self.assertEqual([item["document_id"] for item in filtered_items], ["doc-1", "doc-3"])
        self.assertEqual(resolved_route["scope"]["document_ids"], ["doc-1", "doc-3"])

    def test_build_agentic_tool_request_asks_client_for_metadata_without_sources(self):
        route = parse_query_intent_response(
            '{"query_mode": "extension_filter", "filters": {"extension": "txt"}, '
            '"needs_semantic_context": false}'
        )

        tool_request = build_agentic_tool_request(
            content="какие .txt документы?",
            route=route,
            user_message_id=42,
        )

        self.assertEqual(tool_request["type"], "tool_request")
        self.assertEqual(tool_request["tool"], "list_library")
        self.assertEqual(tool_request["args"]["filters"], {"extension": "txt"})
        self.assertEqual(tool_request["user_message_id"], 42)
        self.assertIn("tool_call_token", tool_request)
        self.assertNotIn("items", tool_request)

    def test_build_agentic_tool_request_asks_client_for_semantic_search(self):
        route = parse_query_intent_response(
            '{"query_mode": "semantic_lookup", "document_ids": ["doc-1"], '
            '"needs_semantic_context": true}'
        )

        tool_request = build_agentic_tool_request(
            content="что сказано про архитектуру?",
            route=route,
            user_message_id=43,
        )

        self.assertEqual(tool_request["tool"], "search_local_documents")
        self.assertEqual(tool_request["args"]["query"], "что сказано про архитектуру?")
        self.assertEqual(tool_request["args"]["document_ids"], ["doc-1"])

    @patch('core.views.generate_completion')
    def test_chat_message_inventory_context_keeps_all_library_sources(self, mock_completion):
        mock_completion.return_value = "В библиотеке есть city_architecture.txt [S1], README.md [S3] и CV_Fedor_Rumiantsev.pdf."

        session_response = self.client.post(reverse('chatsession-list'), {
            "title": "Inventory Sources"
        }, format='json')
        session_id = session_response.data['id']

        message_response = self.client.post(reverse('chat_message_create', kwargs={"session_id": session_id}), {
            "content": "Какие файлы есть у меня в библиотеке?",
            "query_mode": "library_inventory",
            "context_chunks": [
                {
                    "document_id": "city-doc",
                    "filename": "city_architecture.txt",
                    "suggested_title": "city_architecture.txt",
                    "chunk_index": 0,
                    "section_title": "Library Inventory",
                    "reason": "library_inventory",
                    "content": "Filename: city_architecture.txt\nSummary: City story.",
                },
                {
                    "document_id": "large-doc",
                    "filename": "large_test_text_english.txt",
                    "suggested_title": "large_test_text_english.txt",
                    "chunk_index": 0,
                    "section_title": "Library Inventory",
                    "reason": "library_inventory",
                    "content": "Filename: large_test_text_english.txt\nSummary: Large test text.",
                },
                {
                    "document_id": "readme-doc",
                    "filename": "README.md",
                    "suggested_title": "README.md",
                    "chunk_index": 0,
                    "section_title": "Library Inventory",
                    "reason": "library_inventory",
                    "content": "Filename: README.md\nSummary: Source code examples.",
                },
                {
                    "document_id": "cv-doc",
                    "filename": "CV_Fedor_Rumiantsev.pdf",
                    "suggested_title": "Frontend Developer Profile and Experience",
                    "chunk_index": 0,
                    "section_title": "Library Inventory",
                    "reason": "library_inventory",
                    "content": "Filename: CV_Fedor_Rumiantsev.pdf\nSummary: Frontend Engineer profile.",
                },
            ],
        }, format='json')

        self.assertEqual(message_response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(
            [source['document_id'] for source in message_response.data['sources']],
            ['city-doc', 'large-doc', 'readme-doc', 'cv-doc'],
        )

    @patch('core.views.generate_completion')
    def test_chat_message_uses_structured_inventory_items_contract(self, mock_completion):
        mock_completion.return_value = (
            '{"query_mode": "extension_filter", "filters": {"extension": "txt"}, '
            '"needs_semantic_context": false, "confidence": "high"}'
        )

        session_response = self.client.post(reverse('chatsession-list'), {
            "title": "Structured Contract"
        }, format='json')
        session_id = session_response.data['id']

        initial_response = self.client.post(reverse('chat_message_create', kwargs={"session_id": session_id}), {
            "content": "какие из них .txt документы?",
            "query_mode": "llm_routed",
            "scope": {
                "source": "all_documents",
                "document_ids": [],
                "filters": {},
            },
            "retrieval": {"strategy": "llm_router"},
        }, format='json')

        self.assertEqual(initial_response.status_code, status.HTTP_202_ACCEPTED)
        self.assertEqual(initial_response.data["type"], "tool_request")
        self.assertEqual(initial_response.data["tool"], "list_library")
        self.assertEqual(initial_response.data["args"]["filters"], {"extension": "txt"})

        message_response = self.client.post(reverse('chat_message_create', kwargs={"session_id": session_id}), {
            "content": "какие из них .txt документы?",
            "query_mode": "tool_result",
            "user_message_id": initial_response.data["user_message_id"],
            "tool_call_token": initial_response.data["tool_call_token"],
            "tool_result": {
                "tool_call_id": initial_response.data["tool_call_id"],
                "tool_call_token": initial_response.data["tool_call_token"],
                "tool": "list_library",
                "args": initial_response.data["args"],
                "route": initial_response.data["route"],
                "items": [
                    {
                        "document_id": "city-doc",
                        "filename": "city_architecture.txt",
                        "suggested_title": "city_architecture.txt",
                        "content": "Filename: city_architecture.txt\nSummary: City story.",
                    },
                    {
                        "document_id": "large-doc",
                        "filename": "large_test_text_english.txt",
                        "suggested_title": "large_test_text_english.txt",
                        "content": "Filename: large_test_text_english.txt\nSummary: Large text.",
                    },
                    {
                        "document_id": "cv-doc",
                        "filename": "CV_Fedor_Rumiantsev.pdf",
                        "suggested_title": "Frontend Developer Profile and Experience",
                        "content": "Filename: CV_Fedor_Rumiantsev.pdf\nSummary: CV.",
                    },
                ],
            },
        }, format='json')

        self.assertEqual(message_response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(mock_completion.call_count, 1)
        self.assertIn("Найдено 2 .txt документа", message_response.data["content"])
        self.assertEqual(
            [source['document_id'] for source in message_response.data['sources']],
            ['city-doc', 'large-doc'],
        )

    @patch('core.views.generate_completion')
    def test_chat_message_sources_fallback_to_context_when_model_omits_citations(self, mock_completion):
        mock_completion.return_value = "The story is about restoring an old factory for the community."

        session_response = self.client.post(reverse('chatsession-list'), {
            "title": "Citation Fallback"
        }, format='json')
        session_id = session_response.data['id']

        message_response = self.client.post(reverse('chat_message_create', kwargs={"session_id": session_id}), {
            "content": "What is this document about?",
            "query_mode": "semantic_lookup",
            "context_chunks": [{
                "document_id": "story-doc",
                "filename": "factory_story.txt",
                "suggested_title": "Factory Story",
                "chunk_index": 0,
                "section_title": "Document",
                "content": "Mara wants to turn the old factory into a public community space.",
            }],
        }, format='json')

        self.assertEqual(message_response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(message_response.data['sources'][0]['document_id'], 'story-doc')

    @patch('core.views.generate_completion')
    def test_chat_message_returns_assistant_fallback_when_groq_temporarily_fails(self, mock_completion):
        mock_completion.side_effect = RuntimeError("Groq API error (429): rate_limit_exceeded")

        session_response = self.client.post(reverse('chatsession-list'), {
            "title": "Provider Failure"
        }, format='json')
        session_id = session_response.data['id']

        message_response = self.client.post(reverse('chat_message_create', kwargs={"session_id": session_id}), {
            "content": "How did the story end?",
            "query_mode": "semantic_lookup",
            "context_chunks": [{
                "document_id": "story-doc",
                "filename": "factory_story.txt",
                "suggested_title": "Factory Story",
                "chunk_index": 1,
                "section_title": "Ending",
                "content": "The team reopened the factory as a useful public place.",
            }],
        }, format='json')

        self.assertEqual(message_response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(message_response.data['role'], 'assistant')
        self.assertIn('could not generate', message_response.data['content'])
        self.assertEqual(message_response.data['sources'][0]['document_id'], 'story-doc')

    @patch('core.views.generate_completion')
    def test_chat_message_sources_do_not_accumulate_between_answers(self, mock_completion):
        mock_completion.side_effect = [
            "The first answer uses the CV. [S1]",
            "The second answer uses the text file. [S1]",
        ]

        session_response = self.client.post(reverse('chatsession-list'), {
            "title": "Fresh Sources"
        }, format='json')
        session_id = session_response.data['id']
        message_url = reverse('chat_message_create', kwargs={"session_id": session_id})

        first_response = self.client.post(message_url, {
            "content": "What is in the CV?",
            "query_mode": "semantic_lookup",
            "context_chunks": [{
                "document_id": "cv-doc",
                "filename": "CV_Fedor_Rumiantsev.pdf",
                "suggested_title": "CV Fedor",
                "chunk_index": 0,
                "page_number": 1,
                "section_title": "Experience",
                "content": "Experience and employment history.",
            }],
        }, format='json')

        second_response = self.client.post(message_url, {
            "content": "What is in the large text file?",
            "query_mode": "semantic_lookup",
            "context_chunks": [{
                "document_id": "large-text-doc",
                "filename": "large_test_text_english.txt",
                "suggested_title": "large_test_text_english.txt",
                "chunk_index": 0,
                "page_number": 1,
                "section_title": "Document",
                "content": "This text discusses local AI memory systems.",
            }],
        }, format='json')

        self.assertEqual(first_response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(second_response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(first_response.data['sources'][0]['document_id'], 'cv-doc')
        self.assertEqual(second_response.data['sources'][0]['document_id'], 'large-text-doc')

    def test_model_list_reports_single_universal_groq_model(self):
        response = self.client.get(reverse('models_list'))

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['provider'], 'groq')
        self.assertEqual(response.data['fallback_provider'], 'ollama')
        self.assertEqual(response.data['fallback_model'], OLLAMA_LLM_MODEL)
        models = response.data['models']
        self.assertEqual(len(models), 1)
        self.assertEqual(models[0]['name'], GROQ_MODEL)
        self.assertEqual(models[0]['profile'], 'universal')
        self.assertTrue(models[0]['is_default'])

    @patch.dict('os.environ', {'GROQ_API_KEY': 'test-key'})
    @patch('groq_client.requests.post')
    def test_groq_text_completion_uses_universal_model(self, mock_post):
        mock_post.return_value.status_code = status.HTTP_200_OK
        mock_post.return_value.json.return_value = {
            "choices": [{"message": {"content": "text response"}}]
        }

        response = generate_completion("Hello", system_prompt="System")

        self.assertEqual(response, "text response")
        payload = mock_post.call_args.kwargs['json']
        self.assertEqual(payload['model'], GROQ_MODEL)
        self.assertEqual(payload['messages'][0]['role'], 'system')
        self.assertEqual(payload['messages'][1]['content'], 'Hello')

    @patch.dict('os.environ', {'GROQ_API_KEY': 'test-key'})
    @patch('groq_client.generate_ollama_llm_completion')
    @patch('groq_client.requests.post')
    def test_groq_text_completion_falls_back_to_ollama_llm_on_error(self, mock_post, mock_ollama_completion):
        mock_post.return_value.status_code = status.HTTP_429_TOO_MANY_REQUESTS
        mock_post.return_value.json.return_value = {
            "error": {"message": "rate limit", "code": "rate_limit_exceeded"}
        }
        mock_ollama_completion.return_value = "ollama fallback response"

        response = generate_completion("Hello", system_prompt="System")

        self.assertEqual(response, "ollama fallback response")
        mock_ollama_completion.assert_called_once()
        fallback_messages = mock_ollama_completion.call_args.args[0]
        self.assertEqual(fallback_messages[0]['role'], 'system')
        self.assertEqual(fallback_messages[1]['content'], 'Hello')

    @patch.dict('os.environ', {'GROQ_API_KEY': 'test-key'})
    @patch('groq_client.generate_ollama_llm_completion')
    @patch('groq_client.requests.post')
    def test_groq_vision_completion_falls_back_to_ollama_llm_on_error(self, mock_post, mock_ollama_completion):
        mock_post.return_value.status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
        mock_post.return_value.text = "provider error"
        mock_ollama_completion.return_value = "ollama vision fallback response"

        response = generate_vision_completion("Extract text", ["data:image/png;base64,abc"])

        self.assertEqual(response, "ollama vision fallback response")
        fallback_messages = mock_ollama_completion.call_args.args[0]
        self.assertEqual(fallback_messages[-1]['content'][0]['text'], 'Extract text')
        self.assertEqual(fallback_messages[-1]['content'][1]['type'], 'image_url')

    @patch.dict('os.environ', {'GROQ_API_KEY': 'test-key'})
    @patch('groq_client.requests.post')
    def test_groq_vision_completion_uses_universal_model_for_images(self, mock_post):
        mock_post.return_value.status_code = status.HTTP_200_OK
        mock_post.return_value.json.return_value = {
            "choices": [{"message": {"content": "vision response"}}]
        }

        response = generate_vision_completion("Extract text", ["data:image/png;base64,abc"])

        self.assertEqual(response, "vision response")
        payload = mock_post.call_args.kwargs['json']
        self.assertEqual(payload['model'], GROQ_MODEL)
        content = payload['messages'][0]['content']
        self.assertEqual(content[0]['type'], 'text')
        self.assertEqual(content[1]['type'], 'image_url')

    @patch('ollama_llm_client.requests.post')
    def test_ollama_llm_completion_uses_gemma_cloud_chat_endpoint(self, mock_post):
        mock_post.return_value.status_code = status.HTTP_200_OK
        mock_post.return_value.json.return_value = {
            "message": {"content": "ollama response"}
        }

        response = generate_ollama_llm_completion([
            {"role": "system", "content": "System"},
            {"role": "user", "content": "Hello"},
        ])

        self.assertEqual(response, "ollama response")
        self.assertIn('/api/chat', mock_post.call_args.args[0])
        payload = mock_post.call_args.kwargs['json']
        self.assertEqual(payload['model'], OLLAMA_LLM_MODEL)
        self.assertEqual(payload['messages'][1]['content'], 'Hello')

    @patch('ollama_client.get_fallback_model')
    @patch('ollama_client.requests.post')
    def test_ollama_embeddings_use_bge_m3_batch_endpoint(self, mock_post, mock_fallback_model):
        mock_fallback_model.return_value = "bge-m3"
        mock_post.return_value.status_code = status.HTTP_200_OK
        mock_post.return_value.json.return_value = {
            "embeddings": [[0.1, 0.2, 0.3]]
        }

        embeddings = generate_embeddings(["hello world"])

        self.assertEqual(embeddings, [[0.1, 0.2, 0.3]])
        payload = mock_post.call_args.kwargs['json']
        self.assertEqual(payload['model'], OLLAMA_EMBEDDING_MODEL)
        self.assertEqual(payload['input'], ["hello world"])
